### ISSUE TITLE
자바버거 인터페이스 및 클래스 작성

### ISSUE THREAD

**Issue by berryberrybin** [berryberrybin/JavaBurger#10]
자바버거 인터페이스 및 클래스 작성

**Comment by berryberrybin** [comment]
### View
- StartView 클래스 : 프로그램 첫 시작 화면
- menu 패키지
   - RoleMenuView 클래스 : 1. 회원 / 2. 비회원 / 3. 매니저 선택 화면
   - UserMenuView 클래스 : 회원 선택 메뉴 화면
   - OrderMenuView 클래스 : 주문 선택 메뉴 화면
   - ManagerMenuView 클래스 : 매니저 선택 메뉴 화면
- SucessView 클래스 : 성공시 관련 메시지 출력
- FailView 클래스 : 실패시 관련 메시지 출력
- EndView 클래스 : 여러가지 결과 출력

**Comment by berryberrybin** [comment]
### Exception
- AddException : 추가시 발생하는 예외
- DuplicatedException : 중복된 값 발생시 예외
- InvalidMenuException : 유효하지 않는 메뉴 입력시 예외
- ModifyException : 수정시 발생하는 예외
- NotFoundException : 검색시 찾으려는 정보가 없을 경우 예외

**Comment by berryberrybin** [comment]
Controller 추가

**Comment by berryberrybin** [comment]
DAO 추가

**Comment by berryberrybin** [comment]
DTO 추가

**Comment by berryberrybin** [comment]
Service 추가

**Comment by Ella486** [comment]
.
