### ISSUE TITLE
자바버거 ER 다이어그램

### ISSUE THREAD

**Issue by berryberrybin** [berryberrybin/JavaBurger#2]
### 자바버거 ER 다이어그램

![image](https://user-images.githubusercontent.com/67494127/156695147-59d32b71-96f7-4e63-a3b4-ecd704426e05.png)

**Comment by berryberrybin** [comment]
- DB 속성명 명확히 수정

<img src=“https://user-images.githubusercontent.com/67494127/156702028-46848414-c6c2-4988-ac66-75f1da2f40c7.png" width="80%" height="80%">

**Comment by davidoh91** [comment]
**option 테이블 이름 변경**
option -> optional
(option 은 sql 예약어)

**Comment by berryberrybin** [comment]
![image](https://user-images.githubusercontent.com/67494127/156912819-bafb383a-0b47-41b3-8490-b58fab98f669.png)


- 데이터 타입 변경 및 일치
- 테이블 이름 변경
   - Option ->ProductOption
   - User -> UserMemeber
- 필요없는 컬럼삭제
